"""
StockINR — Local Server
========================
Serves dashboard.html and proxies API calls to avoid CORS issues.

Setup:
  export ANTHROPIC_API_KEY="sk-ant-..."   (required)
  python server.py
  Open: http://localhost:5000
"""

import os
import sys
import json
import requests
from flask import Flask, send_file, request, Response

app = Flask(__name__)

ANTHROPIC_API_URL = "https://api.anthropic.com/v1/messages"


def check_api_key():
    """Validate ANTHROPIC_API_KEY at startup and warn clearly if missing."""
    key = os.environ.get("ANTHROPIC_API_KEY", "").strip()
    if not key:
        print("\n" + "!" * 55)
        print("  WARNING: ANTHROPIC_API_KEY is not set!")
        print("  The dashboard will show API errors without it.")
        print()
        print("  Fix: set the environment variable before running:")
        print("    Linux/Mac:  export ANTHROPIC_API_KEY='sk-ant-...'")
        print("    Windows:    set ANTHROPIC_API_KEY=sk-ant-...")
        print("!" * 55 + "\n")
        return False
    masked = key[:8] + "..." + key[-4:]
    print(f"  API Key     : {masked}  ✓")
    return True


@app.route("/")
def index():
    """Serve the dashboard."""
    return send_file("dashboard.html")


@app.route("/api/data")
def serve_report():
    """
    Serve the latest stock report generated by data_processor.py.
    Returns the contents of outputs/report_latest.json.
    """
    report_path = os.path.join("outputs", "report_latest.json")
    if not os.path.exists(report_path):
        return Response(
            json.dumps({
                "error": (
                    "No data file found. "
                    "Please run 'python data_processor.py' first to generate outputs/report_latest.json"
                )
            }),
            status=404,
            content_type="application/json",
        )
    try:
        with open(report_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        return Response(json.dumps(data), status=200, content_type="application/json")
    except Exception as e:
        return Response(
            json.dumps({"error": f"Failed to read report: {str(e)}"}),
            status=500,
            content_type="application/json",
        )


@app.route("/api/claude", methods=["POST"])
def proxy_claude():
    """Proxy requests to Anthropic API to bypass browser CORS restriction."""
    api_key = os.environ.get("ANTHROPIC_API_KEY", "").strip()

    # Return a clear error if the API key is missing
    if not api_key:
        return Response(
            json.dumps({
                "error": {
                    "type": "missing_api_key",
                    "message": (
                        "ANTHROPIC_API_KEY is not set on the server. "
                        "Run: export ANTHROPIC_API_KEY='sk-ant-...' then restart server.py"
                    )
                }
            }),
            status=401,
            content_type="application/json",
        )

    try:
        body = request.get_json()
        if not body:
            return Response(
                json.dumps({"error": {"message": "Empty or invalid JSON body"}}),
                status=400,
                content_type="application/json",
            )

        headers = {
            "Content-Type": "application/json",
            "anthropic-version": "2023-06-01",
            "x-api-key": api_key,
        }

        resp = requests.post(
            ANTHROPIC_API_URL,
            headers=headers,
            json=body,
            timeout=60,
        )

        return Response(
            resp.content,
            status=resp.status_code,
            content_type="application/json",
        )

    except requests.exceptions.Timeout:
        return Response(
            json.dumps({"error": {"message": "Request to Anthropic API timed out (60s)"}}),
            status=504,
            content_type="application/json",
        )
    except requests.exceptions.ConnectionError:
        return Response(
            json.dumps({"error": {"message": "Could not connect to Anthropic API. Check your internet connection."}}),
            status=503,
            content_type="application/json",
        )
    except Exception as e:
        return Response(
            json.dumps({"error": {"message": str(e)}}),
            status=500,
            content_type="application/json",
        )


if __name__ == "__main__":
    print("\n" + "=" * 55)
    print("  StockINR Server")
    print("=" * 55)
    key_ok = check_api_key()
    print(f"  Dashboard   : http://localhost:5000")
    print(f"  Press Ctrl+C to stop")
    print("=" * 55 + "\n")

    if not key_ok:
        print("  Starting anyway — set ANTHROPIC_API_KEY to use the dashboard.\n")

    app.run(host="0.0.0.0", port=5000, debug=False)
